// The gate is exercised end to end against a real repository, because what
// broke it was not its logic but how git reads files: the committed bundles
// carry `-diff` in .gitattributes, git maps that to its built-in binary driver,
// and a scan that skips binary files skipped exactly the file class where a
// leak had already happened once. Only a real repo with real attributes shows
// that, so these tests build one instead of stubbing git.
//
// This file is itself scanned by the gate, so it must contain no forbidden
// literal: the sample path is assembled at runtime.

import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import { makeRepo } from './fixtures/repo.mjs';

const SCRIPT = fileURLToPath(new URL('../scripts/neutrality.mjs', import.meta.url));

const BACKSLASH = String.fromCharCode(92);
/** A local developer path, the shape that once reached a published bundle. */
const LEAKED_PATH = `C:${BACKSLASH}Users${BACKSLASH}dev${BACKSLASH}pr-validator`;

const BUNDLE = 'actions/report/dist/index.mjs';
/** Mirrors the real .gitattributes entry that makes git call the bundles binary. */
const ATTRIBUTES = 'actions/*/dist/index.mjs -diff linguist-generated=true\n';

function runGate(dir) {
  try {
    const stdout = execFileSync(process.execPath, [SCRIPT], {
      cwd: dir,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return { status: 0, stdout, stderr: '' };
  } catch (err) {
    return { status: err.status, stdout: err.stdout ?? '', stderr: err.stderr ?? '' };
  }
}

describe('neutrality gate', () => {
  let repo;

  afterEach(() => {
    repo?.cleanup();
    repo = undefined;
  });

  it('fails and names the file when a committed bundle carries a local path', () => {
    repo = makeRepo({
      baseFiles: {
        '.gitattributes': ATTRIBUTES,
        [BUNDLE]: `// Generated by scripts/build.mjs\nconst raw = '${LEAKED_PATH}';\n`,
      },
    });

    const { status, stderr } = runGate(repo.dir);

    expect(status).toBe(1);
    expect(stderr).toContain(BUNDLE);
  });

  it('passes when the tree is neutral', () => {
    repo = makeRepo({
      baseFiles: {
        '.gitattributes': ATTRIBUTES,
        [BUNDLE]: '// Generated by scripts/build.mjs\nexport const ok = true;\n',
      },
    });

    const { status, stdout } = runGate(repo.dir);

    expect(status).toBe(0);
    expect(stdout).toContain('Neutralidad OK');
  });

  it('refuses to report a clean tree when it did not reach the bundles', () => {
    repo = makeRepo({ baseFiles: { 'src/index.mjs': 'export const ok = true;\n' } });

    const { status, stdout, stderr } = runGate(repo.dir);

    expect(status).toBe(2);
    expect(stderr).toContain('bundle');
    expect(stdout).not.toContain('Neutralidad OK');
  });
});
