#!/usr/bin/env node
// Bundle each entry into the action folder that GitHub executes.
//
// The bundles are committed: GitHub runs an action's code straight from the
// repository, with no install step. `--verify` rebuilds into memory and
// compares against what is committed, so CI fails when someone edits src/
// without rebuilding — the classic way a JS action starts lying about what it
// runs.

import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const VERIFY = process.argv.includes('--verify');

const TARGETS = [
  { entry: 'src/entries/run-check.mjs', out: 'actions/run-check/dist/index.mjs' },
  { entry: 'src/entries/report.mjs', out: 'actions/report/dist/index.mjs' },
];

/**
 * Resolve `./prompt.md?raw` imports to the file's text.
 *
 * Prompts stay as editable Markdown rather than string literals in code, and
 * still end up inlined in the bundle — there is no `src/` on disk at runtime.
 * Vitest gets `?raw` from Vite natively, so both paths read the same file.
 */
const rawTextPlugin = {
  name: 'raw-text',
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /\?raw$/ }, (args) => ({
      path: resolve(args.resolveDir, args.path.replace(/\?raw$/, '')),
      namespace: 'raw-text',
    }));

    pluginBuild.onLoad({ filter: /.*/, namespace: 'raw-text' }, async (args) => ({
      contents: await readFile(args.path, 'utf8'),
      loader: 'text',
    }));
  },
};

async function bundle(entry) {
  const result = await build({
    entryPoints: [join(ROOT, entry)],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    plugins: [rawTextPlugin],
    write: false,
    legalComments: 'none',
    banner: {
      js: '// Generated by scripts/build.mjs — do not edit. Edit src/ and run `npm run build`.',
    },
  });

  return result.outputFiles[0].text;
}

let failed = false;

for (const target of TARGETS) {
  const code = await bundle(target.entry);
  const outPath = join(ROOT, target.out);

  if (VERIFY) {
    let committed = '';
    try {
      committed = await readFile(outPath, 'utf8');
    } catch {
      console.error(`MISSING  ${target.out} — run \`npm run build\``);
      failed = true;
      continue;
    }

    if (committed !== code) {
      console.error(`STALE    ${target.out} — does not match src/, run \`npm run build\``);
      failed = true;
    } else {
      console.log(`OK       ${target.out}`);
    }
    continue;
  }

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, code, 'utf8');
  console.log(`built    ${target.out} (${(code.length / 1024).toFixed(1)} kB)`);
}

process.exit(failed ? 1 : 0);
