#!/usr/bin/env node
// Bundle each entry into the action folder that GitHub executes.
//
// The bundles are committed: GitHub runs an action's code straight from the
// repository, with no install step. `--verify` rebuilds into memory and
// compares against what is committed, so CI fails when someone edits src/
// without rebuilding — the classic way a JS action starts lying about what it
// runs.

import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const VERIFY = process.argv.includes('--verify');

const TARGETS = [
  { entry: 'src/entries/run-check.mjs', out: 'actions/run-check/dist/index.mjs' },
  { entry: 'src/entries/report.mjs', out: 'actions/report/dist/index.mjs' },
];

/**
 * Resolve `./prompt.md?raw` imports to the file's text.
 *
 * Prompts stay as editable Markdown rather than string literals in code, and
 * still end up inlined in the bundle — there is no `src/` on disk at runtime.
 * Vitest gets `?raw` from Vite natively, so both paths read the same file.
 */
const rawTextPlugin = {
  name: 'raw-text',
  setup(pluginBuild) {
    // The resolved path is REPO-RELATIVE, not absolute. esbuild writes the
    // module path into the bundle as a comment, so an absolute path would both
    // make the build unreproducible across machines and publish the author's
    // local directory layout in a public repository.
    pluginBuild.onResolve({ filter: /\?raw$/ }, (args) => ({
      path: relative(ROOT, resolve(args.resolveDir, args.path.replace(/\?raw$/, '')))
        .split(sep)
        .join('/'),
      namespace: 'raw-text',
    }));

    pluginBuild.onLoad({ filter: /.*/, namespace: 'raw-text' }, async (args) => ({
      contents: await readFile(join(ROOT, args.path), 'utf8'),
      loader: 'text',
    }));
  },
};

async function bundle(entry) {
  const result = await build({
    entryPoints: [join(ROOT, entry)],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    plugins: [rawTextPlugin],
    write: false,
    legalComments: 'none',
    banner: {
      js: '// Generated by scripts/build.mjs — do not edit. Edit src/ and run `npm run build`.',
    },
  });

  // Normalise to LF. Some dependencies ship CRLF sources and esbuild preserves
  // them, so the raw output differs from machine to machine. Git then stores
  // the committed bundle as LF, and `--verify` would report a stale bundle on
  // a machine where nothing is wrong. Emitting LF makes the artifact canonical.
  return result.outputFiles[0].text.replace(/\r\n/g, '\n');
}

/** Where two strings first diverge, with a little context around it. */
function firstDifference(a, b) {
  const limit = Math.min(a.length, b.length);
  let i = 0;
  while (i < limit && a[i] === b[i]) i += 1;

  if (i === limit && a.length === b.length) return null;

  const from = Math.max(0, i - 60);
  const to = i + 60;
  return {
    offset: i,
    line: a.slice(0, i).split('\n').length,
    committed: JSON.stringify(a.slice(from, to)),
    rebuilt: JSON.stringify(b.slice(from, to)),
  };
}

let failed = false;

for (const target of TARGETS) {
  const code = await bundle(target.entry);
  const outPath = join(ROOT, target.out);

  if (VERIFY) {
    let committed = '';
    try {
      committed = await readFile(outPath, 'utf8');
    } catch {
      console.error(`MISSING  ${target.out} — run \`npm run build\``);
      failed = true;
      continue;
    }

    if (committed !== code) {
      console.error(`STALE    ${target.out} — does not match src/, run \`npm run build\``);
      const diff = firstDifference(committed, code);
      if (diff) {
        console.error(`         first difference at offset ${diff.offset} (line ~${diff.line})`);
        console.error(`         committed: ${diff.committed}`);
        console.error(`         rebuilt:   ${diff.rebuilt}`);
      } else {
        console.error('         same content, different length — check trailing bytes');
      }
      failed = true;
    } else {
      console.log(`OK       ${target.out}`);
    }
    continue;
  }

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, code, 'utf8');
  console.log(`built    ${target.out} (${(code.length / 1024).toFixed(1)} kB)`);
}

process.exit(failed ? 1 : 0);
