#!/usr/bin/env node
// Bundle each entry into the action folder that GitHub executes, plus the
// local-mode bundle (`dist/local/pr-local.mjs`) that runs on developer machines.
//
// The bundles are committed: GitHub runs an action's code straight from the
// repository, with no install step. `--verify` rebuilds into memory and
// compares against what is committed, so CI fails when someone edits src/
// without rebuilding — the classic way a JS action starts lying about what it
// runs.

import { build } from 'esbuild';
import { realpathSync } from 'node:fs';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveRawImport } from './raw-import.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * `forbid` marks a bundle that must never contain the model client or the task
 * manager client. The local bundle runs on developer machines with no gateway
 * key and no task-manager credentials; if either module were reachable from its
 * entry, the bundle would carry the SDK and the code that reads those secrets
 * for nothing. The build fails instead of trusting nobody to add that import.
 */
export const TARGETS = [
  { name: 'run-check', entry: 'src/entries/run-check.mjs', out: 'actions/run-check/dist/index.mjs' },
  { name: 'report', entry: 'src/entries/report.mjs', out: 'actions/report/dist/index.mjs' },
  {
    name: 'resolve-checks',
    entry: 'src/entries/resolve-checks.mjs',
    out: 'actions/resolve-checks/dist/index.mjs',
  },
  { name: 'local', entry: 'src/entries/local.mjs', out: 'dist/local/pr-local.mjs', forbid: true },
];

/**
 * Resolve `./prompt.md?raw` imports to the file's text.
 *
 * Prompts stay as editable Markdown rather than string literals in code, and
 * still end up inlined in the bundle — there is no `src/` on disk at runtime.
 * Vitest gets `?raw` from Vite natively, so both paths read the same file.
 */
const rawTextPlugin = {
  name: 'raw-text',
  setup(pluginBuild) {
    // `resolveRawImport` decides which file a specifier may reach and returns a
    // REPO-RELATIVE path; it throws for anything outside src/checks/*.md, which
    // esbuild reports as a build error naming the importer. The filter stays
    // broad on purpose: narrowing it would let a rejected specifier fall
    // through to esbuild's own resolution instead of failing the build.
    pluginBuild.onResolve({ filter: /\?raw$/ }, (args) => ({
      path: resolveRawImport(args.path, args.resolveDir, ROOT),
      namespace: 'raw-text',
    }));

    pluginBuild.onLoad({ filter: /.*/, namespace: 'raw-text' }, async (args) => ({
      contents: await readFile(join(ROOT, args.path), 'utf8'),
      loader: 'text',
    }));
  },
};

/** Package specifiers and source modules a `forbid` bundle may not reach. */
const FORBIDDEN_PACKAGE = /^(ai(\/.*)?|@ai-sdk\/.+)$/;
const FORBIDDEN_MODULE = /(^|[\\/])(gateway|tasks-api)\.mjs$/;

/**
 * Fail resolution of the model SDK, the gateway client and the task-manager
 * client. Matching on the import specifier catches a static import, a dynamic
 * `import()` and a re-export alike, and the error names the importer.
 */
export const forbidPlugin = {
  name: 'forbid',
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /.*/ }, (args) => {
      if (args.kind === 'entry-point') return undefined;
      const spec = args.path.replace(/\?.*$/, '');
      if (FORBIDDEN_PACKAGE.test(spec) || FORBIDDEN_MODULE.test(spec)) {
        return {
          errors: [
            {
              text: `"${args.path}" may not be bundled into this target (imported by ${args.importer})`,
            },
          ],
        };
      }
      return undefined;
    });
  },
};

/**
 * Bundle one entry and return the code.
 *
 * @param {string} entry  Repository-relative entry path.
 * @param {{forbid?: boolean}} [opts]
 */
export async function bundle(entry, { forbid = false } = {}) {
  const result = await build({
    entryPoints: [join(ROOT, entry)],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    plugins: forbid ? [forbidPlugin, rawTextPlugin] : [rawTextPlugin],
    write: false,
    legalComments: 'none',
    banner: {
      js: '// Generated by scripts/build.mjs — do not edit. Edit src/ and run `npm run build`.',
    },
  });

  // Normalise to LF. Some dependencies ship CRLF sources and esbuild preserves
  // them, so the raw output differs from machine to machine. Git then stores
  // the committed bundle as LF, and `--verify` would report a stale bundle on
  // a machine where nothing is wrong. Emitting LF makes the artifact canonical.
  return result.outputFiles[0].text.replace(/\r\n/g, '\n');
}

/** Where two strings first diverge, with a little context around it. */
function firstDifference(a, b) {
  const limit = Math.min(a.length, b.length);
  let i = 0;
  while (i < limit && a[i] === b[i]) i += 1;

  if (i === limit && a.length === b.length) return null;

  const from = Math.max(0, i - 60);
  const to = i + 60;
  return {
    offset: i,
    line: a.slice(0, i).split('\n').length,
    committed: JSON.stringify(a.slice(from, to)),
    rebuilt: JSON.stringify(b.slice(from, to)),
  };
}

/**
 * Build, or with `--verify` compare, every target. `--only <name>` limits the
 * run to one target.
 *
 * @returns {Promise<number>} the exit code.
 */
async function run(argv) {
  const verify = argv.includes('--verify');
  const onlyIndex = argv.indexOf('--only');
  const only = onlyIndex === -1 ? null : argv[onlyIndex + 1];
  const targets = only ? TARGETS.filter((target) => target.name === only) : TARGETS;
  if (only && !targets.length) {
    console.error(`unknown target "${only}". Targets: ${TARGETS.map((t) => t.name).join(', ')}`);
    return 1;
  }

  let failed = false;

  for (const target of targets) {
    const code = await bundle(target.entry, { forbid: target.forbid });
    const outPath = join(ROOT, target.out);

    if (verify) {
      let committed = '';
      try {
        committed = await readFile(outPath, 'utf8');
      } catch {
        console.error(`MISSING  ${target.out} — run \`npm run build\``);
        failed = true;
        continue;
      }

      if (committed !== code) {
        console.error(`STALE    ${target.out} — does not match src/, run \`npm run build\``);
        const diff = firstDifference(committed, code);
        if (diff) {
          console.error(`         first difference at offset ${diff.offset} (line ~${diff.line})`);
          console.error(`         committed: ${diff.committed}`);
          console.error(`         rebuilt:   ${diff.rebuilt}`);
        } else {
          console.error('         same content, different length — check trailing bytes');
        }
        failed = true;
      } else {
        console.log(`OK       ${target.out}`);
      }
      continue;
    }

    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, code, 'utf8');
    console.log(`built    ${target.out} (${(code.length / 1024).toFixed(1)} kB)`);
  }

  return failed ? 1 : 0;
}

/**
 * Is this file the script node was asked to run? Compared through realpath,
 * and case-insensitively on Windows, where the drive letter's case depends on
 * how the shell spelled the path. A false negative here would turn the build
 * into a silent no-op that exits 0.
 */
function invokedDirectly() {
  if (!process.argv[1]) return false;
  try {
    const self = realpathSync(fileURLToPath(import.meta.url));
    const invoked = realpathSync(process.argv[1]);
    return process.platform === 'win32'
      ? self.toLowerCase() === invoked.toLowerCase()
      : self === invoked;
  } catch {
    return false;
  }
}

// Importable by the tests without building anything.
if (invokedDirectly()) {
  process.exit(await run(process.argv.slice(2)));
}
